### **feature encoding**

![alt text](data/dst-eda-3-8.jpg)

In [1]:
import pandas as pd
import category_encoders as ce

In [2]:
clothing_list = [
    ['xxs', 'dress'],
    ['xxs', 'skirt'],
    ['xs', 'dress'],
    ['s', 'skirt'],
    ['m', 'dress'],
    ['l', 'shirt'],
    ['s', 'coat'],
    ['m', 'coat'],
    ['xxl', 'shirt'],
    ['l', 'dress']
]

clothing = pd.DataFrame(clothing_list, columns = ['size',  'type'])
clothing

  size   type
0  xxs  dress
1  xxs  skirt
2   xs  dress
3    s  skirt
4    m  dress
5    l  shirt
6    s   coat
7    m   coat
8  xxl  shirt
9    l  dress

### **Ordinal Encoding**

![alt text](data/asset-v1_SkillFactory+DST-3.0+28FEB2021+type@asset+block@dst-eda-3-9.png)

In [3]:
# создаем объект OrdinalEncoder, col - имя столбца, mapping - словарь с описанием кодировки
ord_encoder = ce.OrdinalEncoder(mapping=[{
	'col': 'size',
	'mapping': {'xxs': 1, 'xs': 2, 's': 3, 
                'm': 4, 'l': 5, 'xxl': 6}
}])
# применяем трансформацию к столбцу
data_bin = ord_encoder.fit_transform(clothing[['size']])
# добавляем результат к исходному DataFrame
clothing = pd.concat([clothing, data_bin], axis=1)

clothing

  size   type  size
0  xxs  dress     1
1  xxs  skirt     1
2   xs  dress     2
3    s  skirt     3
4    m  dress     4
5    l  shirt     5
6    s   coat     3
7    m   coat     4
8  xxl  shirt     6
9    l  dress     5

### **One-Hot Encoding**

![alt text](data/dst-eda-3-11.png)

In [5]:
encoder = ce.OneHotEncoder(cols=['type'], use_cat_names=True) # указываем столбец для кодирования
type_bin = encoder.fit_transform(clothing['type'])
clothing = pd.concat([clothing, type_bin], axis=1)

clothing

  size   type  size  type_dress  type_skirt  type_shirt  type_coat
0  xxs  dress     1           1           0           0          0
1  xxs  skirt     1           0           1           0          0
2   xs  dress     2           1           0           0          0
3    s  skirt     3           0           1           0          0
4    m  dress     4           1           0           0          0
5    l  shirt     5           0           0           1          0
6    s   coat     3           0           0           0          1
7    m   coat     4           0           0           0          1
8  xxl  shirt     6           0           0           1          0
9    l  dress     5           1           0           0          0

### **Binary Encoding**

![alt text](data/dst-eda-3-14.png)

In [6]:
bin_encoder = ce.BinaryEncoder(cols=['type']) # указываем столбец для кодирования
type_bin = bin_encoder.fit_transform(clothing['type'])
clothing = pd.concat([clothing, type_bin], axis=1)

clothing

,size,type,size,type_dress,type_skirt,type_shirt,type_coat,type_0,type_1,type_2
0,xxs,dress,1,1,0,0,0,0,0,1
1,xxs,skirt,1,0,1,0,0,0,1,0
2,xs,dress,2,1,0,0,0,0,0,1
3,s,skirt,3,0,1,0,0,0,1,0
4,m,dress,4,1,0,0,0,0,0,1
5,l,shirt,5,0,0,1,0,0,1,1
6,s,coat,3,0,0,0,1,1,0,0
7,m,coat,4,0,0,0,1,1,0,0
8,xxl,shirt,6,0,0,1,0,0,1,1
9,l,dress,5,1,0,0,0,0,0,1

### a bit of practice

In [ ]:
list_of_dicts = [
 {'product': 'Product1', 'price': 1200, 'payment_type': 'Mastercard'},
 {'product': 'Product2', 'price': 3600, 'payment_type': 'Visa'},
 {'product': 'Product3', 'price': 7500, 'payment_type': 'Amex'}
]
df = pd.DataFrame(list_of_dicts)
# product ordinal encoder
ord_code = ce.OrdinalEncoder(mapping=[{
    'col':'product',
    'mapping':{'Product1':1, 'Product2':2, 'Product3':3}
}])
prod_code = ord_code.fit_transform(df['product'])
df = pd.concat([df, prod_code], axis=1)
# onehot encoder payment_type
onehot_code = ce.OneHotEncoder(cols=['payment_type'], use_cat_names=True)
payment_code = onehot_code.fit_transform(df['payment_type'])
df = pd.concat([df, payment_code], axis=1)

,product,price,payment_type,product,payment_type_Mastercard,payment_type_Visa,payment_type_Amex
0,Product1,1200,Mastercard,1,1,0,0
1,Product2,3600,Visa,2,0,1,0
2,Product3,7500,Amex,3,0,0,1